name: 📦 Publish qwrk-vite on tag

on:
  push:
    tags:
      - "qwrk-vite@*"

jobs:
  publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/qwrk-vite

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"
          always-auth: true

      - name: Install dependencies
        run: npm ci

      - name: Publish to npm registry
        run: npm publish --access public --provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
